language: python
before_install:
  - sudo apt update
  - sudo apt -y install jq python-tz python3 python-yaml
  - sudo wget -O /usr/bin/umoci http://people.ubuntu.com/~serge-hallyn/umoci.static
  - sudo chmod ugo+x /usr/bin/umoci
script:
  - sudo ./test_genoci.sh
notifications:
  email:
    recipients:
      shallyn@cisco.com
